#!/usr/bin/env bash

set -o errexit

function error {
	echo "error: $1"
	exit 1
}

function signin {
	# Get current account from op config
	if [ -f "$HOME/.op/config" ]; then
		ACCOUNT=$(jq '.accounts | .[] | .shorthand' "$HOME/.op/config" --raw-output) || error "error getting op config"
		echo $(op signin "${ACCOUNT}")
	else
		op "$@"
	fi
}

function get {
	if [[ "$2" == "password" ]]; then
		ITEM=$(op get item $3)
		if [ $? -ne 0 ]; then
			error "${ITEM}"
		fi
		echo "${ITEM}" | jq '.details.fields[] | select(.designation=="password").value' --raw-output
	else
		op "$@"
	fi
}

function generate {
	PASSWORD=$(openssl rand -base64 32)
	if [ $? -ne 0 ]; then
		error "${PASSWORD}"
	fi
	echo "${PASSWORD}"
}

function export_logins {
	if [ -z "$1" ]; then
		FILE="$(date "+%Y%m%d-%H%M%S")-1password.json"
	else
		if [ -f "$1" ]; then
			error "file already exists '$1'"
		else
			FILE=$1
		fi
	fi

	echo -ne "Exporting logins (this may take a while)... "
	ITEMS=$(op list items)
	if [ $? -ne 0 ]; then
		error "${ITEMS}"
	fi
	UUIDS=($(echo "${ITEMS}" | jq '.[] | .uuid' --raw-output))
	ITEMS=()

	for UUID in ${UUIDS[@]}; do
		LOGIN=$(op get item "${UUID}")
		if [ $? -eq 0 ]; then
			ITEMS+=(${LOGIN})
		fi
	done
	echo ${ITEMS[@]} | jq -sc . > "${FILE}"
	echo -ne "ok\r\n"	
}

# Check requirements
command -v op &> /dev/null || error "required program 'op' is not installed"
command -v jq &> /dev/null || error "required program 'jq' is not installed"
command -v openssl &> /dev/null || error "required program 'openssl' is not installed"

case "$1" in
	signin)
		signin "$@"
		;;
	get)
		get "$@"
		;;
	generate)
		generate "$@"
		;;
	export)
		export_logins $2
		;;
	*)
		op "$@"
		;;
esac
